### ISSUE TITLE
Some SVG nodes from util toolkit are not receiving user input by default

### ISSUE THREAD

**Issue by shamansir** [shamansir/rpd#425]
Set `pointer-events: all` to all of them, like that:

```css
.rpd-util-nodelist .rpd-process *,
.rpd-util-dial .rpd-process *,
.rpd-util-knob .rpd-process * {
    pointer-events: all;
}
```
